---
# create a new VM from a template

- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: uhmc-vcenter02
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "abcd123"
    esxhost: vmhost-ucs-02.uhmc.sunysb.edu
    datastore: uhmc_vol_nfs_dev04
    vmtemplate: russ2016template
    name: "russ-test-deploy01"
    notes: Ansible Test
    dumpfacts: False
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxhost }}"
        datacenter: SBUMC
        name: "{{ name }}"
        template: "{{ vmtemplate }}"
        folder: /Automation (Russ)
        disk:
          - size_gb: "{{ disk_size | default(50) }}"
            type: thin
            datastore: "{{ datastore }}"
        networks:
        - name: dvVM_Sysadmin
          type: dhcp
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: False
        state: present
      register: newvm

    - name: IP address info
      debug:
        msg: "{{ newvm.instance.ipv4 }} {{ name }}"